config/routes.rb
Rails.application.routes.draw do
  
  root 'static_page#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, except: [:index, :show, :edit] 
  get '/profile/:id', to: 'users#show', as: "profile"
  get '/profile/:id/addresses/new', to: 'addresses#new', as: "new_address"
  get '/profile/:user_id/addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  put '/profile/:user_id/addresses/:id/', to: 'addresses#update', as: "update_address"
  delete '/profile/:user_id/addresses/:id/', to: 'addresses#destroy', as: "delete_address"
  resources :addresses, except: [:show, :index]

  get '/profile/:id/edit', to: 'users#edit', as: "edit"
  get '/menus', to: 'menus#index'
  get '/about_us', to: 'static_page#about_us'
  resources :contact_us, only: :index
  get 'my_purchases', to: 'my_purchases#index' 
  resources :menus, only: :show do
    resources :orders, only: [:create, :new] do
      member do
        get '/cancel', to: 'orders#cancel'
        get '/preparing', to: 'orders#preparing'
        get '/shipping', to: 'orders#shipping'
        get '/complete', to: 'orders#complete'
      end
    end
  end

  

  namespace :admin do
    
    get 'dashboard', to: 'dashboard#index'
    resources :users, only: [:index, :show]
    get '/profile/:id', to: 'users#show', as: "profile"
    resources :menus do
      resources :orders, only: [:create, :new] do
        member do
          get '/cancel', to: 'orders#cancel'
          get '/preparing', to: 'orders#preparing'
          get '/shipping', to: 'orders#shipping'
          get '/complete', to: 'orders#complete'
        end
      end
    end
    resources :contact_us, only: :index
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/billing.rb
class Billing < Address
  belongs_to :user
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  has_many :orders
  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  enum status: [:in_cart, :uncart, :preparing, :shipping, :complete]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :in_cart
  end
end

app/models/user.rb
class User < ApplicationRecord
  # before_save not working
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :orders

  has_one_attached :avatar

  has_many :addresses

  validates :contact, numericality: { only_integer: true }, length: { in: 9..11}

  def set_default_role
    self.role ||= :user
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

  def home
    @menu = Menu.all
  end

  def about_us
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user

  def require_user
    unless current_user.user?
      redirect_to root_path
    end
  end

  def index
    @users = User.where(role: "user")
  end

  def show
    @billing = Billing.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      if current_user.user?
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,  :avatar, :contact)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user(id)
    user = User.find(id)
    user.email
  end

  def title(id)
    menu = Menu.find(id)
    menu.title
  end

  def price(id)
    menu = Menu.find(id)
    menu.price
  end

  def status(id)
    menu = Menu.find(id)
    menu.status
  end

  def total(price, quantity)
    menu = Menu.find(price)
    menu.price * quantity
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/menus_helper.rb
module MenusHelper

  def total_menu
    return Menu.all.count
  end
end

app/helpers/my_purchases_helper.rb
module MyPurchasesHelper

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_preparing
    preparing = Order.where(status: "preparing", user_id: current_user.id ).count
    if preparing == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_shipping
    shipping = Order.where(status: "shipping", user_id: current_user.id ).count
    if shipping == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_complete
    complete = Order.where(status: "complete", user_id: current_user.id ).count
    if complete == 0
      return "Nothing to display"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_page/_about.html.erb
<section id="about" class="about">
  <div class="section-header">About</div>
  <div class="content">
    <h3>Admin</h3>
    <h4>Username: admin@test.com</h4>
    <h4>Password: 123456</h4>
    <h3>User 1</h3>
    <h4>Username: user1@test.com</h4>
    <h4>Password: 123456</h4>
  </div>

</section>

app/views/static_page/_contact_us.html.erb
<section class="contact-us " >
  <div class="section-header section-contact" id="contact-us">Contact Us</div>
  <div class="contact-wrapper">
    <div class="contact-details">
      <div class="phone">
        <i class="fas fa-mobile-alt"></i>
        <h3>Phone</h3>
        <p>+123 456 789</p>
        <p>+987 654 321</p>
      </div>
      <div class="address">
        <i class="fas fa-map-marker-alt"></i>
        <h3>Address</h3>
        <p>30 Edsa, corner Pioneer St, </p>
        <p>Mandaluyong, Metro Manila</p>
      </div>
      <div class="email">
        <i class="far fa-envelope"></i>
        <h3>Email</h3>
        <p>noemail@test.com</p>
        <p>test@test.com</p>
      </div>
    </div>
    <h1>Get In Touch</h1>
    <form class="contact-form">
      <input type="text" placeholder="Your Name">
      <input type="email" placeholder="Your Email">
      <textarea placeholder="Your Message"></textarea>
      <input type="submit" value="Send Message">
    </form>
  </div>
</section>

app/views/static_page/_home.html.erb
<section id="home" class="home">
  <div class="left-side">
    <h1 class="primary">There are endless combinations of coffee that could be drank</h1>
    <h3 class="sub">You know how to make a simple cup of coffee, but what about a Vietnamese Cha Phe Sua Da? And do you know the difference between a macchiato and a cappuccino? <span>It’s always up to us to find the right one.</span> </h3>
    <%= link_to signup_path do %>
      <button class="button singup">Sign up</button>
    <% end %>
  </div>
  <div class="right-side">
    <%= image_tag "hero.svg", style: 'height:80%;width:80%;' %>
  </div>
</section>

app/views/static_page/_menu.html.erb
<section id="menu" class="menu">
  <h1 class="section-header">Menu</h1>

  <div class="menu-content">
    <% @menu.each do |menu| %>
      <div class="menu-card">
        <div class="coffee_img">
          <% if menu.image.attached? %>
            <%= image_tag(menu.image) %>
          <% else %>
            <%= image_tag "coffee.svg"%>
          <% end %>            
        </div>
        <h1 class="title"><%= menu.title %></h1>
        <h3 class="description"><%= menu.description %></h3>
        <h2 class="price"><%= menu.price %><span> PHP</span> </h2>
        <div class="card-btn">
          <% if logged_in? %>
            <%= link_to  new_menu_order_path(menu) do %>
              <button class="button buy_now">Buy</button>
            <% end %>
          <% else %>
            <%= link_to  login_path do %>
              <button class="button buy_now">Buy</button>
            <% end %>
          <% end %>
          
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/static_page/about_us.html.erb
<section id="about" class="about_us">
  <div class="section-header">About Us</div>
  <div class="content">
    <h3>Admin</h3>
    <h4>Username: admin@test.com</h4>
    <h4>Password: 123456</h4>
    <h3>User 1</h3>
    <h4>Username: user1@test.com</h4>
    <h4>Password: 123456</h4>
  </div>

</section>

app/views/static_page/home.html.erb
<section id="home" class="home">
  <div class="left-side">
    <h1 class="primary">There are endless combinations of coffee that could be drank</h1>
    <h3 class="sub">You know how to make a simple cup of coffee, but what about a Vietnamese Cha Phe Sua Da? And do you know the difference between a macchiato and a cappuccino? <span>It’s always up to us to find the right one.</span> </h3>
    <%= link_to signup_path do %>
      <button class="button singup">Sign up</button>
    <% end %>
  </div>
  <div class="right-side">
    <%= image_tag "hero.svg", style: 'height:80%;width:80%;' %>
  </div>
</section>