config/routes.rb
Rails.application.routes.draw do
  
  root 'static_page#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, except: [:index, :show, :edit] 
  get '/profile/:id', to: 'users#show', as: "profile"
  get '/profile/:id/addresses/new', to: 'addresses#new', as: "new_address"
  get '/profile/:user_id/addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  put '/profile/:user_id/addresses/:id/', to: 'addresses#update', as: "update_address"
  delete '/profile/:user_id/addresses/:id/', to: 'addresses#destroy', as: "delete_address"
  resources :addresses, except: [:show, :index]

  get '/profile/:id/edit', to: 'users#edit', as: "edit"
  get '/menus', to: 'menus#index'
  get '/about_us', to: 'static_page#about_us'
  resources :contact_us, only: :index
  get 'my_purchases', to: 'my_purchases#index' 
  resources :menus, only: :show do
    resources :orders, only: [:create, :new] do
      member do
        get '/cancel', to: 'orders#cancel'
        get '/preparing', to: 'orders#preparing'
        get '/shipping', to: 'orders#shipping'
        get '/complete', to: 'orders#complete'
      end
    end
  end

  

  namespace :admin do
    
    get 'dashboard', to: 'dashboard#index'
    resources :users, only: [:index, :show]
    get '/profile/:id', to: 'users#show', as: "profile"
    resources :menus do
      resources :orders, only: [:create, :new] do
        member do
          get '/cancel', to: 'orders#cancel'
          get '/preparing', to: 'orders#preparing'
          get '/shipping', to: 'orders#shipping'
          get '/complete', to: 'orders#complete'
        end
      end
    end
    resources :contact_us, only: :index
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/billing.rb
class Billing < Address
  belongs_to :user
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  has_many :orders
  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  enum status: [:in_cart, :uncart, :preparing, :shipping, :complete]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :in_cart
  end
end

app/models/user.rb
class User < ApplicationRecord
  # before_save not working
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :orders

  has_one_attached :avatar

  has_many :addresses

  validates :contact, numericality: { only_integer: true }, length: { in: 9..11}

  def set_default_role
    self.role ||= :user
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @incart = Order.where(status: "in_cart")
    @preparing = Order.where(status: "preparing")
    @shipping = Order.where(status: "shipping")
    @complete = Order.where(status: "complete")
  end
  

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user

  def require_user
    unless current_user.user?
      redirect_to root_path
    end
  end

  def index
    @users = User.where(role: "user")
  end

  def show
    @billing = Billing.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      if current_user.user?
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,  :avatar, :contact)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user(id)
    user = User.find(id)
    user.email
  end

  def title(id)
    menu = Menu.find(id)
    menu.title
  end

  def price(id)
    menu = Menu.find(id)
    menu.price
  end

  def status(id)
    menu = Menu.find(id)
    menu.status
  end

  def total(price, quantity)
    menu = Menu.find(price)
    menu.price * quantity
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/menus_helper.rb
module MenusHelper

  def total_menu
    return Menu.all.count
  end
end

app/helpers/my_purchases_helper.rb
module MyPurchasesHelper

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_preparing
    preparing = Order.where(status: "preparing", user_id: current_user.id ).count
    if preparing == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_shipping
    shipping = Order.where(status: "shipping", user_id: current_user.id ).count
    if shipping == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_complete
    complete = Order.where(status: "complete", user_id: current_user.id ).count
    if complete == 0
      return "Nothing to display"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<div class="section">  
  <button class="tablink" onclick="openPage('pending_order', this, '#777')">Pending</button>
  <button class="tablink" onclick="openPage('preparing_order', this, '#777')" id="defaultOpen">Preparing</button>
  <button class="tablink" onclick="openPage('shipping_order', this, '#777')">Shipping</button>
  <button class="tablink" onclick="openPage('complete_order', this, '#777')">Completed</button>

  <div id="pending_order" class="tabcontent">
    <div class="cart">
      <h1 class="center">Order in Cart</h1>
      <table class="table order_table">
        <tr>
          <th class="order-20">Customer</th>
          <th class="order-20">Coffee</th>
          <th class="order-10">Price</th>
          <th class="order-10">quantity</th>
          <th class="order-20">total</th>
          <th class="order-20 center">action</th>
        </tr>
        <% @incart.each do |incart| %>
        <tr>
          <td>
            <%= link_to admin_user_path(incart.user_id) do %>
              <%= user(incart.user_id) %> 
            <% end %>
          </td>
          <td><%= title(incart.menu_id) %> </td>
          <td><%= price(incart.menu_id) %> </td>
          <td><%= incart.quantity %> </td>
          <td><%= total(incart.menu_id, incart.quantity)%> </td>
          <td class="order-20 center">
            <%= link_to preparing_menu_order_path(incart.menu_id, incart.id) do %>
              <button class=" dashboar-btn">Move to preparing</button>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div id="preparing_order" class="tabcontent">
    <div class="preparing">
      <h1 class="center">Order Preparing</h1>
      <table class="table order_table">
        <tr>
          <th>Customer</th>
          <th>Coffee</th>
          <th>Price</th>
          <th>quantity</th>
          <th>total</th>
          <th class="order-20 center">action</th>
        </tr>
        <% @preparing.each do |preparing| %>
        <tr>
          <td>
          <%= link_to admin_user_path(preparing.user_id) do %>
              <%= user(preparing.user_id) %> 
            <% end %>
            </td>
          <td><%= title(preparing.menu_id) %> </td>
          <td><%= price(preparing.menu_id) %> </td>
          <td><%= preparing.quantity %> </td>
          <td><%= total(preparing.menu_id, preparing.quantity)%> </td>
          <td>
            <%= link_to shipping_menu_order_path(preparing.menu_id, preparing.id) do %>
              <button class=" dashboar-btn">Move to shippment<button>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div id="shipping_order" class="tabcontent">
    <div class="shipping">
      <h1 class="center">Shipping</h1>
      <table class="table order_table">
        <tr>
          <th>Customer</th>
          <th>Coffee</th>
          <th>Price</th>
          <th>quantity</th>
          <th>total</th>
          <th  class="order-20 center">action</th>
        </tr>
        <% @shipping.each do |shipping| %>
        <tr>
          <td>
            <%= link_to admin_user_path(shipping.user_id) do %>
              <%= user(shipping.user_id) %> 
            <% end %>
          </td>
          <td><%= title(shipping.menu_id) %> </td>
          <td><%= price(shipping.menu_id) %> </td>
          <td><%= shipping.quantity %> </td>
          <td><%= total(shipping.menu_id, shipping.quantity)%> </td>
          <td>
            <%= link_to complete_menu_order_path(shipping.menu_id, shipping.id) do %>
            <button class=" dashboar-btn">Move to complete<button>
            <% end %>  
          </td>
        </tr>
        <% end %>
      </table>
    </div>

  </div>

  <div id="complete_order" class="tabcontent">
    <div class="complete">
      <h1 class="center">complete</h1>
      <table class="order_table">
        <tr>
          <th>Customer</th>
          <th>Coffee</th>
          <th>Price</th>
          <th>quantity</th>
          <th>total</th>
        </tr>
        <% @complete.each do |complete| %>
        <tr>
          <td>
            <%= link_to admin_user_path(complete.user_id) do %>
              <%= user(complete.user_id) %> 
            <% end %>
          </td>
          <td><%= title(complete.menu_id) %> </td>
          <td><%= price(complete.menu_id) %> </td>
          <td><%= complete.quantity %> </td>
          <td><%= total(complete.menu_id, complete.quantity)%> </td>
        </tr>
        <% end %>
      </table>
    
    </div>

  </div>
</div>

<%= javascript_include_tag 'dashboard'%>