config/routes.rb
Rails.application.routes.draw do
  
  root 'static_page#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, except: [:index, :show, :edit] 
  get '/profile/:id', to: 'users#show', as: "profile"
  get '/profile/:id/addresses/new', to: 'addresses#new', as: "new_address"
  get '/profile/:user_id/addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  put '/profile/:user_id/addresses/:id/', to: 'addresses#update', as: "update_address"
  delete '/profile/:user_id/addresses/:id/', to: 'addresses#destroy', as: "delete_address"
  resources :addresses, except: [:show, :index]

  get '/profile/:id/edit', to: 'users#edit', as: "edit"
  get '/menus', to: 'menus#index'
  get '/about_us', to: 'static_page#about_us'
  resources :contact_us, only: :index
  get 'my_purchases', to: 'my_purchases#index' 
  resources :menus, only: :show do
    resources :orders, only: [:create, :new] do
      member do
        get '/cancel', to: 'orders#cancel'
        get '/preparing', to: 'orders#preparing'
        get '/shipping', to: 'orders#shipping'
        get '/complete', to: 'orders#complete'
      end
    end
  end

  

  namespace :admin do
    
    get 'dashboard', to: 'dashboard#index'
    resources :users, only: [:index, :show]
    get '/profile/:id', to: 'users#show', as: "profile"
    resources :menus do
      resources :orders, only: [:create, :new] do
        member do
          get '/cancel', to: 'orders#cancel'
          get '/preparing', to: 'orders#preparing'
          get '/shipping', to: 'orders#shipping'
          get '/complete', to: 'orders#complete'
        end
      end
    end
    resources :contact_us, only: :index
  end
end

app/models/user.rb
class User < ApplicationRecord
  # before_save not working
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :orders

  has_one_attached :avatar

  has_many :addresses

  validates :contact, numericality: { only_integer: true }, length: { in: 9..11}

  def set_default_role
    self.role ||= :user
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: :show
  before_action :require_admin

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
  

  def index
    @users = User.where(role: "user")
    @all_user_count = User.where(role: "user").size
  end

  def show
    @admin = User.where(role: "admin")
  end

  private
    def set_user
      if current_user.admin?
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user

  def require_user
    unless current_user.user?
      redirect_to root_path
    end
  end

  def index
    @users = User.where(role: "user")
  end

  def show
    @billing = Billing.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      if current_user.user?
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,  :avatar, :contact)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form">
<%= form_with(model: @user) do |form| %>
  <%= render 'shared/error_messages' %>

  <div>
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label "Confirmation", style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="action">
    <%= form.submit do %>
      <button class="button">Sign Up</button>
    <% end %>
  </div>
<% end %>

</div>

app/views/users/_user.html.erb
  <div class=" section profile">
    <div class="left">
      <div class="image">
          
      </div>
    </div>
    <div class="right">
        <h1 class="center title">Profile</h1>
        <div class="avatar">
    
            <% if @user.avatar.attached? %>
              <%= image_tag(@user.avatar) %>
            <% else %>
              <%= image_tag "No_profile.jpg"%>
            <% end %>  
  
        </div>
        
        <h2 class="profile-label" >Name: <span> <%= @user.name %> </span></h2>
        <hr size="3" noshade width="70%">
        <h2 class="profile-label" >Email: <span> <%= @user.email %></span></h2>
        <hr size="3" noshade width="70%">
        <h2 class="profile-label" >Contact: <span> <%= @user.contact %></span></h2>
        <hr size="3" noshade width="70%">
        <h2 class="profile-label" >Adress: <span>
          <table >
          <% @user.addresses.each do |a| %>
            <tr>
              <td><%= a.street1 %> <%= a.street2 %>, <%= a.city %> <%= a.province %> <%= a.zip %></td>
              <td><%= link_to "edit", edit_address_path(@user, a) %></td>
              <td><%= link_to "delete", delete_address_path(@user,a), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }  %></td>
            </tr>
            <% end %>
          </table>
        </span></h2>
        <h2><%= link_to "New Address", new_address_path %></h2>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="section">
  <h1 class="center">Editing user</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/new.html.erb
<section class="signup">
<h1 class="title">New user</h1>
<%= render "form", user: @user %>

</section>

app/views/users/show.html.erb
<div class=" section ">
  <%= render 'users/user' %>
  <div class="button-end">
    <%= link_to edit_path(@user) do %>
      <button class="button">Edit</button>
    <% end %>
  </div>
</div>