config/routes.rb
Rails.application.routes.draw do
  
  root 'static_page#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, except: [:index, :show, :edit] 
  get '/profile/:id', to: 'users#show', as: "profile"
  get '/profile/:id/addresses/new', to: 'addresses#new', as: "new_address"
  get '/profile/:user_id/addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  put '/profile/:user_id/addresses/:id/', to: 'addresses#update', as: "update_address"
  delete '/profile/:user_id/addresses/:id/', to: 'addresses#destroy', as: "delete_address"
  resources :addresses, except: [:show, :index]

  get '/profile/:id/edit', to: 'users#edit', as: "edit"
  get '/menus', to: 'menus#index'
  get '/about_us', to: 'static_page#about_us'
  resources :contact_us, only: :index
  get 'my_purchases', to: 'my_purchases#index' 
  resources :menus, only: :show do
    resources :orders, only: [:create, :new] do
      member do
        get '/cancel', to: 'orders#cancel'
        get '/preparing', to: 'orders#preparing'
        get '/shipping', to: 'orders#shipping'
        get '/complete', to: 'orders#complete'
      end
    end
  end

  

  namespace :admin do
    
    get 'dashboard', to: 'dashboard#index'
    resources :users, only: [:index, :show]
    get '/profile/:id', to: 'users#show', as: "profile"
    resources :menus do
      resources :orders, only: [:create, :new] do
        member do
          get '/cancel', to: 'orders#cancel'
          get '/preparing', to: 'orders#preparing'
          get '/shipping', to: 'orders#shipping'
          get '/complete', to: 'orders#complete'
        end
      end
    end
    resources :contact_us, only: :index
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/billing.rb
class Billing < Address
  belongs_to :user
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  has_many :orders
  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu

  enum status: [:in_cart, :uncart, :preparing, :shipping, :complete]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :in_cart
  end
end

app/models/user.rb
class User < ApplicationRecord
  # before_save not working
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :orders

  has_one_attached :avatar

  has_many :addresses

  validates :contact, numericality: { only_integer: true }, length: { in: 9..11}

  def set_default_role
    self.role ||= :user
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user(id)
    user = User.find(id)
    user.email
  end

  def title(id)
    menu = Menu.find(id)
    menu.title
  end

  def price(id)
    menu = Menu.find(id)
    menu.price
  end

  def status(id)
    menu = Menu.find(id)
    menu.status
  end

  def total(price, quantity)
    menu = Menu.find(price)
    menu.price * quantity
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/menus_helper.rb
module MenusHelper

  def total_menu
    return Menu.all.count
  end
end

app/helpers/my_purchases_helper.rb
module MyPurchasesHelper

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_cart
    cart = Order.where(status: "in_cart", user_id: current_user.id ).count
    if cart == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_preparing
    preparing = Order.where(status: "preparing", user_id: current_user.id ).count
    if preparing == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_shipping
    shipping = Order.where(status: "shipping", user_id: current_user.id ).count
    if shipping == 0
      return "Nothing to display"
    end
  end

  def nothing_to_display_complete
    complete = Order.where(status: "complete", user_id: current_user.id ).count
    if complete == 0
      return "Nothing to display"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.erb
<section class="header">
  <h1 class="logo"><%= link_to "Coffee Time", root_path%> </h1>
  <nav class="navbar">
    <% if logged_in? && current_user.user? %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Menu', menus_path %>
      <%= link_to 'About Us',  about_us_path %>
      <%= link_to 'Contact Us', contact_us_path %>
    <% elsif logged_in? && current_user.admin? %>
      <%= link_to "Dashboard", admin_dashboard_path %>
      <%= link_to "Menu", admin_menus_path %>
      <%= link_to "Users", admin_users_path %>
      <%= link_to 'Contact us', admin_contact_us_path %>
    <% else %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Menu', menus_path %>
      <%= link_to 'About Us', about_us_path %>
      <%= link_to 'Contact us', contact_us_path %>
    <% end %>
  </nav>
  <div class="user-navbar dropdown">
    <% if logged_in? %>
      <span class="user" ><%= current_user.name %></span>
      <div class="navbar-content dropdown-content">
          <% if current_user.admin? %>
            <%= link_to "Profile", admin_profile_path(current_user.id) %>
          <% elsif current_user.user? %>
            <%= link_to "Profile", profile_path(current_user.id) %>
            <%= link_to "My Order", my_purchases_path %>
          <% end %>
          <%= link_to "Log out", logout_path, method: :delete %>
     
      </div>     
    <% else %>
      <%= link_to login_path do %>
        <button class="login">Login</button>
      <% end %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= javascript_tag 'dashboard' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>